### ISSUE TITLE
"Unsupported Ops of type: AddV2" error while using convert.py

### ISSUE THREAD

**Issue by geozhai** [infocom-tpo/PoseNet-CoreML#12]
Hey, I keep getting this error while using convert.py. Any idea on how to fix it?

`Traceback (most recent call last):
  File "convert.py", line 56, in <module>
    image_scale = 2./255)
  File "/usr/local/lib/python3.6/dist-packages/tfcoreml/_tf_coreml_converter.py", line 715, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/usr/local/lib/python3.6/dist-packages/tfcoreml/_tf_coreml_converter.py", line 359, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names, effectively_constant_ops + unused_ops)
  File "/usr/local/lib/python3.6/dist-packages/tfcoreml/_tf_coreml_converter.py", line 188, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: AddV2`

coremltools==3.1
Tensorflow=1.14.0
Python=3.6.9
tfcoreml =1.0

**Comment by mbotsu** [comment]
See here https://github.com/infocom-tpo/PoseNet-CoreML/issues/10
